### ISSUE TITLE
Implement multiple spot bidding strategies

### ISSUE THREAD

**Issue by cristim** [cristim/autospotting#119]
# Feature idea #

Add support for multiple bidding strategies, configurable on a per-group level.

## Detailed explanation ##

At the moment the only supported strategy is hardcoded to bid the original on-demand instance's hourly price for any spot instances added to the group.

This is quite safe and is suitable for production use where longer-running instances are desirable, but it fails to handle the spot price increases that don't go over the on-demand price but are significantly higher than when the instance was launched, and may be not the most cost-efficient strategy.

Alternate strategies may be to place the currently spot price plus a configurable margin, such as 10%, which would capture most significant spot price increases.

An absolute margin may also be desirable, allowing to place bids a fraction of a cent over the current price, which would aggressively optimize for cost savings since the last runtime hour before spot termination is free of charge.

For best results this may need to be coupled with the spot-to-spot replacement to be implemented in #118, in order to avoid the cost incurred by running temporary on-demand instances.

**Comment by briantyr** [comment]
Good write up - I can see this being a long-term goal to become much more attractive to CIO's / those that "pay the bills" to be able to configure multiple bidding strategies.  Good catch noting all that down in the description @cristim

**Comment by cristim** [comment]
@briantyr please have a look, we now have an initial implementation of this feature.

Feel free to give it a try and it would be great if you could give us some feedback about this.

**Comment by deinspanjer** [comment]
Very exciting!  It will be a couple of weeks before I'll be able to actually test it out, but I'll read over the patch and any implementation doc and provide feedback where and as soon as I can.
