### ISSUE TITLE
Document new feature regarding types

### ISSUE THREAD

**Issue by xlr-8** [cristim/autospotting#121]
## Build number #

Any

## Configuration ##

Linked to new option for instance types

## Environment ##

Any

## Summary ##

This is a very minor issue, due to the recent merge of a pull request.

The recent feature that has been merged for specifying the instance type, which somehow solves https://github.com/cristim/autospotting/issues/47 (as by whitelisting certain, you by default blacklist the others) has however not update the documentation, such as: 
https://github.com/cristim/autospotting/blob/master/START.md#configuration-of-autospotting

## Steps to reproduce ##

Non needed

**Comment by cristim** [comment]
as reported on #120 the functionality configuration isn't working for some users. This definitely needs more testing before we document it as supported.
