### ISSUE TITLE
Code contribution checklist

### ISSUE THREAD

**Issue by cristim** [cristim/autospotting#122]
# Github issue #

## Issue type ##

- Documentation Report

## Summary ##

Document the code contribution requirements into a clear checklist in order to ensure the high quality of code contributions and a faster approval process with less code review ping-pong (the goal is to avoid what happened in #120 and #121 going forward).

It should cover things like:
- contribution scope
- coding style
- automated test coverage
- configurability
- manual test results

## Expected results ##

The issue template used for new PRs should contain a checklist detailing the requirements expected to be satisfied by new code contributions.

**Comment by cristim** [comment]
@raravena80 please have a look at this, hopefully it speeds up code reviews going forward.

**Comment by raravena80** [comment]
@cristim looks good to me. The question I have is where that document should exist?

**Comment by cristim** [comment]
It's under the standard path used by github as skeleton for the text of new PRs.

I will link to it also from the contribution guide document. Currently it's just mentioned there but it's not yet linked.
