### ISSUE TITLE
 detachAndTerminateOnDemandInstance should use TerminateInstanceInAutoScalingGroup

### ISSUE THREAD

**Issue by cristim** [cristim/autospotting#138]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

The current logic issues a detach followed by a termination.
`TerminateInstanceInAutoScalingGroup` would do these for us, slightly simplifying the replacement logic.

**Comment by francoran** [comment]
@cristim I think that if we'll replace the detach logic then connection draining will not take place as it sends termination request to the instance. I didn't test it

**Comment by cristim** [comment]
@francoran can you also test the patch in #141? I'd like to have that merged but I can't do it before it's confirmed to work as expected and for now I have no bandwidth to thoroughly test this.

**Comment by phils** [comment]
@cristim  @francoran I use TerminateInstanceInAutoScalingGroup (via awscli) all the time in production and it definitely does ELB connection draining.

**Comment by xlr-8** [comment]
I'm reopening this issue based on https://github.com/cristim/autospotting/pull/241/files

**Comment by cristim** [comment]
Fixed in #287, closing issue
