### ISSUE TITLE
Does "spot fleet" make this project obsolete?

### ISSUE THREAD

**Issue by JensRantil** [cristim/autospotting#139]
Does "spot fleet" make this project obsolete? It feels like it's basically the same thing.

**Comment by cristim** [comment]
Not, even though they are similar, they solve different problems and each have a certain niche.

Please have a look at the [FAQ](https://etherpad.net/p/AutoSpotting_FAQ) for more details.

**Comment by JensRantil** [comment]
Ok. Thanks for quick response!
