### ISSUE TITLE
Elastic IP

### ISSUE THREAD

**Issue by arvalaan** [cristim/autospotting#144]
Dear all, thanks for this amazing repo. It'll prob save me hundreds of euros every month for my bootstrapped startup. One thing I'm wondering on how to solve is how do I get AutoSpotting to assign the same Elastic IP (or Network Controller) to the newly created instance?

Thanks!

**Comment by cristim** [comment]
Thanks @arvalaan, and good luck with your project.

Autospotting doesn't currently handle Elastic IPs, you should do it from your userdata script, by running some awscli commands.

**Comment by xlr-8** [comment]
**Please note that this is untested**

I drafted quickly something like this: 
```bash
#!/bin/bash

IPS="52.31.18.103 34.251.114.123"
INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
IPS_AVAILABLE=$(aws ec2 describe-addresses --public-ips ${IPS} --query 'Addresses[?AssociationId==null]')

if [ "$(echo ${IPS_AVAILABLE} | jq '. | length')" == 0 ]; then
	echo "No IP available"
	exit 1
fi

FIRST_IP=$(echo ${IPS_AVAILABLE} | jq '.Addresses[0].PublicIp' | tr -d '"')
aws ec2 associate-address --instance-id ${INSTANCE_ID} --public-ip ${FIRST_IP} && echo "Successfuly associated" || (echo "Couldn't associate IP"; exit 2)
```

You would have to provide a preselected list of IP addresses (or remove it if you don't need it), and add some more testing/logging but that's the idea. Hope that helps.

**Comment by arvalaan** [comment]
Thanks a lot for the quick replies. @xlr-8 I'll give your script a spin and report back here!
