### ISSUE TITLE
Feature: specify quantity of spot instances per spot request

### ISSUE THREAD

**Issue by russellballestrini** [cristim/autospotting#145]
# Feature #

Allow operator to specify the quantity of spot instances per spot request.  Current default is hard coded to 1.  

## Issue type ##

Feature Enhancement

## Build number #

All

## Environment ##

- us-east-1
- VPC

## Summary ##

Because the default is 1, after 50 spot requests you hit you following limit - 

Spot Fleet Limits

The usual Amazon EC2 limits apply to instances launched by a Spot fleet, such as Spot bid price limits, instance limits, and volume limits. In addition, the following limits apply:

The number of active Spot fleets per region: 1,000
The number of launch specifications per fleet: 50

Reference: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html

**Comment by xlr-8** [comment]
It sounds like something that could be done by updating some of the logic parts: especially regarding the limits of spots instances per asg.

However, if I may ask a silly question - considering how AWS are willing to update limits - wouldn't it be something faster to ask AWS to increase that limit rather than update the code?

Please note that the question is mostly to solve your problem faster, not to deny the enhancement request.

**Comment by cristim** [comment]
This is definitely doable with reasonable effort but I would prefer not to complicate the logic for something that can be addressed by a simple limit increase.

I'm open to discuss this further and reopen it if a limit increase isn't enough.

**Comment by russellballestrini** [comment]
I also prefer to keep the logic simple.

Another reason for this configuration option is to speed up the roll out of spot instances to a larger ASG. If on average it takes 10 minutes per spot instance it could take a about over a day to roll out to a 100 node ASG. Still not a show stopper by any means.

Thanks for reviewing this idea. : )

**Comment by cristim** [comment]
Thanks, this actually makes sense, ideally the group configuration should converge within an hour or two, at most.

I'm thinking of doing multiple replacements in parallel, maybe about 20% of the group capacity, but not necessarily using multiple instances per spot request, but simply launching multiple spot requests  in parallel. This would still need a limit increase but would converge faster and may be simpler/cleaner  to implement than with multiple instances per spot request.

But I would like to see some code for both approaches, it's much easier to talk about it and compare the options when also having some code.

@russellballestrini Please feel free to create PRs for both these approaches if this is really important to you.
