### ISSUE TITLE
what happens when a server is out bid?

### ISSUE THREAD

**Issue by brenguy** [cristim/autospotting#148]
- Documentation Report

What happens to an autoscaling group when one of the spot instances gets terminated due to being outbidded? Will the autospotting lambda function recognize this? Does an on-demand instance get launched to replace that spot instance? and if so does autospotting try to replace that instance?

**Comment by cristim** [comment]
> What happens to an autoscaling group when one of the spot instances gets terminated due to being outbidded?
Nothing immediately, the group will eventually notice it failed the health checks and replace it with an on-demand one, which AutoSpotting will try to replace with spot later. 
> Will the autospotting lambda function recognize this?
No, this is AutoScaling's job.
> Does an on-demand instance get launched to replace that spot instance?
Yes, eventually. 
> and if so does autospotting try to replace that instance?
Yes.

**Comment by josegonzalez** [comment]
Seems like this can be closed?

**Comment by cristim** [comment]
@josegonzales, @brenguy do you think this behavior should be better documented or mentioned in the FAQ?

Feel free to create a PR if you have any further improvement suggestions.
