### ISSUE TITLE
On-Demand Replacement Draining 

### ISSUE THREAD

**Issue by francoran** [cristim/autospotting#150]
Hi,

In FAQ  - https://github.com/cristim/autospotting/blob/master/FAQ.md#how-is-the-spot-instance-replacement-working
There that line that describe the behavior when replacement of on-demand instance happens -  
> If the spot instance is past its grace period, AutoSpotting will attach it to the group and immediately detach and terminate an on-demand instance from the same availability zone.

As I need ~1m for draining an instance before termination and make sure there are not requests in the pipe I wanted to know if AutoSpotting will respect the draining period I've set on the ASG.
I know I can implement my own solution for dealing with **termination notice of spot instances**, but my question is about the **on-demand instances** in the group as I see it mentioned that it will immediately detach and terminate the on-demand instance.

Thanks,

**Comment by cristim** [comment]
Autospotting just triggers the termination after detaching the on demand instance. What happens afterwards is not currently handled.

I didn't test it, but as far as I know, this will immediately detach the instance from the load balancer, which is supposed to be done after the traffic is drained.

Please test this and report back the results, this should be documented somewhere.

In any case, you can always configure a lifecycle hook that implements the draining logic.

**Comment by francoran** [comment]
Tested, I think we're good :)

Moreover - As explained here - http://docs.aws.amazon.com/autoscaling/latest/userguide/detach-instance-asg.html

> If you detach an instance from an Auto Scaling group that has an attached load balancer, the instance is deregistered from the load balancer. If you detach an instance from an Auto Scaling group that has an attached target group, the instance is deregistered from the target group. If connection draining is enabled for your load balancer, Auto Scaling waits for in-flight requests to complete.

Good to mention- 
While the replacement happened, the ELB had no instance inside its group so 0 of 0 instance where in service for 20 seconds until it recognized the newly attached instance.

**Comment by cristim** [comment]
That's expected, in general you should only run groups of a single instance in case you can afford brief periods of downtime. 

This is just exacerbated and rendered more visible by the volatile spot instances and autospotting's replacement logic which makes it even more visible.
