### ISSUE TITLE
not clear with percent maths

### ISSUE THREAD

**Issue by prashantdj1** [cristim/autospotting#157]
# Github issue #

Can you explain how it works if cluster is 2 or 4. Not able to understand how much percent we need to keep for different cluster size. Also will it work with number and percent both at the same time or it will be only one.

## Issue type ##

- Bug Report
- Feature Idea
- Documentation Report

## Build number #

```text
```

## Environment ##

- AWS region
- Type of environment: (VPC, EC2Classic or DefaultVPC)
- Anonymized launch configuration: 

```text
```

## Actual results ##

```text
```

**Comment by russellballestrini** [comment]
@prashantdj1 choose either:

* a number
* a percentage
* empty

If you choose not to provide autospotting with a number or a percent, autospotting will replace every on-demand instance, one-at-a-time with a spot instance. This is the prefered configuration unless you already have Reserved instances.

**Comment by cristim** [comment]
If I remember correctly when both are set currently the number is used and the percentage is ignored.

I would like to have this behavior configurable or to take the maximum, like for a group of 4, the number 1 and 50% would give 2, currently this would result in a single one.

**Comment by xlr-8** [comment]
Hello, documentation was made [here](https://github.com/cristim/autospotting/blob/master/START.md#minimum-on-demand-configuration) to explain the priority.

Percentage will work as you expect, if you specify a percentage value which has a comma, then consider checking the note to see how the rounding functions.

**Comment by cristim** [comment]
I think this behavior is documented well enough, so I propose we close this.

@prashandtj1 If you think that section of the documentation is not easy to find or not clear enough, please create a PR with a proposed improvement, we'll gladly consider it.
