### ISSUE TITLE
Spot requests fail when no SSH key is configured

### ISSUE THREAD

**Issue by snordhausen** [cristim/autospotting#16]
Hi!

While playing around with autospotting, I configured a Launch Configuration that did not define an SSH key. In this setup, the spot requests failed with this error message:
```
failed: Invalid value '' for keyPairNames. It should not be blank (400 response code)
bad-parameters: Your Spot request failed due to bad parameters.
```
It would be nice if autospotting supported this setup.

**Comment by cristim** [comment]
AutoSpotting couldn't care less about this, but unfortunately it seems the AWS spot request needs that field, even if AutoScaling doesn't need it.

It's likely one of those cases that show how AWS EC2 was built by different teams that didn't really care about synchronizing their JSON fields.

You can try launching a spot request with the AWS CLI tool that is also missing the SSH key field, if that works, then it is indeed an autospotting bug and I'll have to look into it in more detail.

**Comment by snordhausen** [comment]
I tried it out using the AWS CLI. When the field was empty, I got exactly the error message that autospotting produced. But when I completely removed the KeyName field from the JSON, the request works and I get an instance. Autospotting would have to do the same.

**Comment by cristim** [comment]
Thanks, that's great information and looks like an easy fix. Patches are always welcome :-)

**Comment by cristim** [comment]
Reopening, pending user confirmation.

@snordhausen please let me know if you still notice this issue, it should now be fixed.

**Comment by snordhausen** [comment]
Works as it should. Thanks for the quick fix!

**Comment by cristim** [comment]
@snordhausen Thanks for the confirmation, please let me know if you notice any other issues.
