### ISSUE TITLE
Tag spot instances with the original LC name.

### ISSUE THREAD

**Issue by andrewmcgilvray** [cristim/autospotting#165]
## Issue type ##
- Feature Idea

## Build number #

commit 6ddeb4a5f1eb444c34952c7f11ad873a355fe572

```
diff --git a/core/autoscaling.go b/core/autoscaling.go
index 378b088..316e48b 100644
--- a/core/autoscaling.go
+++ b/core/autoscaling.go
@@ -280,6 +280,10 @@ func (a *autoScalingGroup) propagatedInstanceTags() []*ec2.Tag {
                        })
                }
        }
+       tags = append(tags, &ec2.Tag{
+               Key:   aws.String("LaunchConfigurationName"),
+               Value: a.LaunchConfigurationName,
+       })
        return tags
 }
```

## Summary ##

It is nice to have the replacement spot instances tagged with the Launch Configuration Name they were launched with.

**Comment by cristim** [comment]
Thanks for the proposal.

Is this tag/information present on the original on demand instances?

Please explain the use case why this is useful, and what value this provides.

**Comment by cristim** [comment]
Okay, it makes sense. Please create a PR with this change and I will get it through.

**Comment by xlr-8** [comment]
I got a bit tired of seeing this issue open, so here you go: https://github.com/cristim/autospotting/pull/219.

⚠️  I haven't tested it, so @cristim & @andrewmcgilvray please give it a try and tell me what you think about it.
