### ISSUE TITLE
Switch to basic Go environment for Lambda

### ISSUE THREAD

**Issue by xlr-8** [cristim/autospotting#170]
## Issue type ##

- Feature Idea

## Summary ##

Switch the project to the default Lambda go runtime provided by AWS.

## Details ##

Since the AWS re:invent, the Go support for Lambda has been announced, so instead of using tricks to build a binary and then make it run under Python runtime, it would be best to use directly the runtime environment provided by AWS.

Note: it is not yet available in eu-west-1 console for example, so need to wait.

**Comment by cristim** [comment]
As far as I can see the native go support for Lambda is not yet generally available. 

But we should definitely switch to it once it is released.

**Comment by cristim** [comment]
I had a look at the official Go Lambda runtime and it seems like it may take a bit of work to get it also build as a command line tool, but the Lambda function build process looks significantly simpler than what we have now.

**Comment by xlr-8** [comment]
I have made an updated version that seem to run fine so far with Terraform - Cloudformation was also updated with the same logic but not yet tested.

I have to double check the Makefile rules and verify I can run it locally - or find a way to do so - and we should be good.

**Comment by cristim** [comment]
Worked like a charm, huge thanks for this awesome contribution!

**Comment by xlr-8** [comment]
Soon X-Ray coming! :smiley:
