### ISSUE TITLE
Improve feature visibility of the project's features

### ISSUE THREAD

**Issue by xlr-8** [cristim/autospotting#174]
## Issue type ##

- Documentation Report

## Summary ##

Add an array/matrix of features / statuses.

## Details ##

When seeing various issues [tagged as Epic](https://github.com/cristim/autospotting/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3AEpic+) or even some such as: https://github.com/cristim/autospotting/issues/150, I feel that it could be good to have in our documentation an array or matrix of features being already done, not done, in progress etc.

That would not only increase the visibility of how rich the project is, but also provide quick insight on what has been done, or will be done/not done soon. Having it automatically generated based on the issue labeling/statuses would be great, as it could turn to be a pain to maintain.

**Comment by cristim** [comment]
Here's a small wishlist I have from this:

- additional columns for having the feature exposed via Terraform and CloudFormation, since experimental features may not be exposed from the start, but just run as command-line options during development.
- a field for the maturity of each feature.

In the second table
- entries for  DefaultVPC, EC2Classic and VPC.
- some lines added about ECS, Kubernetes, Rancher, Mesos, Nomad, etc.(with links to docs and tools that allow draining the workload) such as https://github.com/kube-aws/kube-spot-termination-notice-handler, etc.

**Comment by xlr-8** [comment]
OK, so I added couple elements you requested: https://github.com/cristim/autospotting/blob/hr-174/TECHNICAL_DETAILS.md#summary-of-supported-features--options

As mentioned in the commit message, I've also added "bugs" and the linked issue, to be more clear/transparent about it.

However, there isn't always doc referencing options & such, as mentioned in the commit.

Regarding the other desires, I'm a bit reserved.

**features exposed via Terraform/Cloudformation**
I don't think documenting features while developing is such a good idea, whether it is stable or it isn't. But I wouldn't document it as part of the "official documentation" - I'd rather have that in a changelog or something, then when stable/merged in the documentation.

**maturity**
How do you evaluate and maintain the maturity's level of a feature? By date of introduction? By number of bug reported about it? By feedback from the users?

**draining workload**
I've added Rancher, which made quite some sense to me; but I'm uncertain the link you provided is linked with autospotting - I haven't read it thoroughly, so I might have missed it - regarding the others, do you have specific links in mind?

**Comment by cristim** [comment]
Looks great, thanks!

Regarding the others:

> **features exposed via Terraform/Cloudformation**
> I don't think documenting features while developing is such a good idea, whether it is stable or it isn't. 
> But I wouldn't document it as part of the "official documentation" - I'd rather have that in a changelog or something, then when stable/merged in the documentation.

It may be a good chance for people to see that things are being worked on (nor necessarily buggy, just maybe partially implemented), so they can help with testing or to finish the implementation. We can't expect from all contributors to install Terraform just for exposing the feature to Terraform users, and the same applies for Terraform users who shouldn't be expected to author the CloudFormation code. Every contributor is expected to scratch his own itch, and that's okay, even if features are not all evolved to the same degree.

> **maturity**
> How do you evaluate and maintain the maturity's level of a feature? By date of introduction? By number of bug reported about it? By feedback from the users?
I think feedback accumulated within a few months from when the feature landed should be a good indicator.

> **draining workload**
> I've added Rancher, which made quite some sense to me; but I'm uncertain the link you provided is linked with autospotting - I haven't read it thoroughly, so I might have missed it - regarding the others, do you have specific links in mind? 
- That's okay for Rancher.
- Kubernetes: https://github.com/mumoshu/kube-spot-termination-notice-handler
- ECS: maybe this? https://github.com/ktruckenmiller/aws-ecs-spot-instance-drainer 
- Mesos & Nomad: couldn't find anything within a short search

**Comment by xlr-8** [comment]
Thinking about it adding Linux/Windows support could be a thing as well
