### ISSUE TITLE
make full-test don't run properly

### ISSUE THREAD

**Issue by xlr-8** [cristim/autospotting#178]
## Issue type ##

- Bug Report

## Build number #

Latest, the test failing are most likely introduced in `e3921a0b` or `4f31c4a6`.

## Configuration ##

Master's head clone.

## Environment ##

Any.

## Summary ##

The `make full-test` doesn't run properly as some comments are not properly formatted.

## Steps to reproduce ##

Clone master, run `make full-test`.

## Expected results ##

```bash
(master|✔)> make full-test
ok	all files passed go fmt
ok	all files passed go vet
ok  	github.com/cristim/autospotting/core	0.012s	coverage: 71.2% of statements
```

## Actual results ##

```bash
(master|✔)> make full-test
ok	all files passed go fmt
ok	all files passed go vet
ok  	github.com/cristim/autospotting/core	0.013s	coverage: 71.1% of statements
autospotting.go:22:1: comment on exported var Version should be of the form "Version ..."
autospotting.go:24:5: exported var ExpirationDate should have comment or be unexported
Found 2 lint suggestions; failing.
make: *** [Makefile:93: lint] Error 1
```

**Comment by cristim** [comment]
Interesting, wasn't this executed on CI?

**Comment by xlr-8** [comment]
No the lint rule was missing, I updated the PR related to it.
