### ISSUE TITLE
Working with Elastic Beanstalk

### ISSUE THREAD

**Issue by roeyazroel** [cristim/autospotting#18]
Just tested it with Elastic Beanstalk - working great. just add the tags during creation of new environment.

Maybe add to README?

Roey

**Comment by cristim** [comment]
Thanks @roeyazroel for testing it, great to know it works!

It is actually mentioned in the Features, let me know if that's fine or should I make it more proeminent.

**Comment by roeyazroel** [comment]
The ECS feature is go without saying, But the Elastic Beanstalk is more complected, has you can't update the ASG tags from the environment. You will need to find the ASG that the EBS is working with, and then manually update. every time the environment will be rebuild or solution stack will be updated, you might lose the tag. So updating the ASG tags from the environment configuration is safer. And the process of updating the environment tags isn't friendly at all.

**Comment by cristim** [comment]
I understand, it would be great to have that Beanstalk stuff documented into a dedicated markdown page linked to the readme. Please create a pull request.

**Comment by cristim** [comment]
Fixed in #34

**Comment by cristim** [comment]
Beanstalk recently added the ability to easily tag resoiurces, see [here](https://aws.amazon.com/about-aws/whats-new/2017/10/aws-elastic-beanstalk-supports-ability-to-update-tags) 

I think we should update the documentation accordingly.

**Comment by roeyazroel** [comment]
@cristim well, it's look like you can replace the entire section on beanstalk by "update the environment tags". 👍

**Comment by cristim** [comment]
I think this can be closed
