### ISSUE TITLE
AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.

### ISSUE THREAD

**Issue by binarylogic** [cristim/autospotting#187]
# Github issue #

## Issue type ##

- Bug Report

## Build number #

```text
build nightly-517 expiring on 09-Feb-2018
```

## Summary ##

Today we started seeing the below error in our logs. We're using the terraform module and the below error suggests that we need to add the `iam:CreateServiceLinkedRole` permission to the `autospotting` role. This seems odd given no one else has reported it, and I'm confident it's something on our end. Any idea what might be going on? If we do need to add that permission I'm happy to make a pull request with the change. Thanks!

## Actual results ##

Here's what we see the CW logs:

```text
2017/12/13 23:31:17 autoscaling.go:611: Failed to create spot instance request for app-name AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.
```

**Comment by xlr-8** [comment]
Indeed that's weird, I've been playing a bit with it tonight and didn't face that issue.

Could you provide more information about the versions your using tools & co / configuration of the environment / reproducibility of your situation? Eventually turn on the [debug mode](https://github.com/cristim/autospotting/blob/master/START.md#debug-autospotting)?

Have you also check the limits of spot requests? - even though it doesn't sound like it. Did you try adding the policy to observe the change of behavior?

**Comment by cristim** [comment]
@binarylogic Can you share the configuration of the IAM role set on the on-demand instances?

Maybe there's some stuff that triggers a requirement of this permission for the spot instances.

**Comment by binarylogic** [comment]
Sure thing. Adding the `iam:CreateServiceLinkedRole` permission to the `autospotting` role resolved the issue, but this requires deviating from the provided terraform scripts.

### IAM role for the EC2 on-demand instance

STS:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowEC2Assume",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

Policy 1:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ReleaseDownloadAccess",
            "Effect": "Allow",
            "Action": [
                "s3:ListObjects",
                "s3:GetObjectVersion",
                "s3:GetObject"
            ],
            "Resource": "[redacted]"
        },
        {
            "Sid": "ReleaseListingAccess",
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "[redacted]"
        },
        {
            "Sid": "DownloadCodeDeployAgent",
            "Effect": "Allow",
            "Action": [
                "s3:List*",
                "s3:Get*"
            ],
            "Resource": ["[redacted]"]
        },
        {
            "Sid": "MetricsAccess",
            "Effect": "Allow",
            "Action": "cloudwatch:PutMetricData",
            "Resource": "[redacted]"
        },
        {
            "Sid": "GetSystemStateManager",
            "Effect": "Allow",
            "Action": [
                "ssm:UpdateInstanceInformation",
                "ssm:UpdateInstanceAssociationStatus",
                "ssm:UpdateAssociationStatus",
                "ssm:PutInventory",
                "ssm:ListInstanceAssociations",
                "ssm:ListAssociations",
                "ssm:GetParameters",
                "ssm:GetDocument",
                "ssm:DescribeAssociation"
            ],
            "Resource": "[redacted]"
        },
        {
            "Sid": "AllowEC2Messages",
            "Effect": "Allow",
            "Action": [
                "ec2messages:SendReply",
                "ec2messages:GetMessages",
                "ec2messages:GetEndpoint",
                "ec2messages:FailMessage",
                "ec2messages:DeleteMessage",
                "ec2messages:AcknowledgeMessage"
            ],
            "Resource": "[redacted]"
        },
        {
            "Sid": "AllowEC2InstanceStatus",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeTags",
                "ec2:DescribeInstanceStatus"
            ],
            "Resource": "[redacted]"
        },
        {
            "Sid": "AllowDirectories",
            "Effect": "Allow",
            "Action": [
                "ds:DescribeDirectories",
                "ds:CreateComputer"
            ],
            "Resource": "[redacted]"
        },
        {
            "Sid": "AllowCloudwatchLogging",
            "Effect": "Allow",
            "Action": [
                "logs:PutLogEvents",
                "logs:DescribeLogStreams",
                "logs:DescribeLogGroups",
                "logs:CreateLogStream",
                "logs:CreateLogGroup"
            ],
            "Resource": "[redacted]"
        }
    ]
}
```

Policy 2:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AWSDynamoDBTableApplicationColumnsReadAccess",
            "Effect": "Allow",
            "Action": "dynamodb:Query",
            "Resource": "[redacted]"
        },
        {
            "Sid": "AWSDynamoDBTableClientLogsHiveIngestionLeases",
            "Effect": "Allow",
            "Action": [
                "dynamodb:UpdateItem",
                "dynamodb:PutItem",
                "dynamodb:GetItem"
            ],
            "Resource": "[redacted]"
        },
        {
            "Sid": "AWSDynamoDBTableS3PartitionsAccess",
            "Effect": "Allow",
            "Action": [
                "dynamodb:UpdateItem",
                "dynamodb:Query",
                "dynamodb:PutItem",
                "dynamodb:GetItem"
            ],
            "Resource": "[redacted]"
        },
        {
            "Sid": "AWSKinesisStreamLogLinesReaderAccess",
            "Effect": "Allow",
            "Action": [
                "kinesis:List*",
                "kinesis:Get*",
                "kinesis:Describe*"
            ],
            "Resource": "[redacted]"
        },
        {
            "Sid": "AWSS3BucketClientLogsAccess",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": "[redacted]"
        },
        {
            "Sid": "AWSSQSHiveTablePartitionMaintainingConsumeAccess",
            "Effect": "Allow",
            "Action": "sqs:SendMessage",
            "Resource": "[redacted]"
        }
    ]
}
```

Policy 3:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "codedeploy:Batch*",
                "codedeploy:CreateDeployment",
                "codedeploy:Get*",
                "codedeploy:List*",
                "codedeploy:RegisterApplicationRevision"
            ],
            "Effect": "Allow",
            "Resource": "[redacted]"
        }
    ]
}
```

**Comment by cristim** [comment]
Thanks, you have a fair amount of rules. Would you be willing to bisect the policies to find out which of the rules requires this?

We can get this documented for now but if the rule is likely to be used by many people I am open to adding this permission to the list.

**Comment by homme** [comment]
I just came across this issue as well and had to add the `sts:AssumeRole` permission to the `autospotting` role in addition to the `iam:CreateServiceLinkedRole` mentioned above in order to fix it.

**Comment by cristim** [comment]
I would like to keep the IAM permissions to the minimum required to run, but I agree to add things that are really required, I just want to understand what kind of IAM rules trigger this requirement, since this wasn't the case for most users.

@homme, @binarylogic can you help us determine this?

**Comment by binarylogic** [comment]
I've narrowed it down to the CodeDeploy permissions.

An easier solution might be just to export the `aws_iam_role .autospotting_role.name` which would allow us to use the [`aws_iam_role_policy_attachment` function](https://www.terraform.io/docs/providers/aws/r/iam_role_policy_attachment.html) and attach our own custom policies.

**Comment by kkopachev** [comment]
Same happened with our system. We use ECS cluster created with SpotInstances only. Upon creation it created ecsSpotFleetRole and attached managed AmazonEC2SpotFleetRole to it. Then we added spot-only autoscaling to it so it was automatically going up and down. 
Recently it failed to bring up new instances with the same error as above. My assumption was since we use AWS-managed policy, it would just work.
Attaching inline policy with `iam:CreateServiceLinkedRole` fixed the issue. It finally created new "service-linked role" and works fine at the moment.
Looking at IAM console, we noticed there are several service-linked roles created automatically in past week or so. 

Looks like that forgot to add some permissions to create such role: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-requests.html#service-linked-roles-spot-fleet-requests
> If you had an active Spot Fleet request before November 2017, when Amazon EC2 began supporting this service-linked role, Amazon EC2 created the AWSServiceRoleForEC2SpotFleet role in your AWS account.

I suspect that creation of such role beforehand would just work.

**Comment by cristim** [comment]
Okay,I see this is quite widespread, let's add this to the list of permissions.

I will gladly accept a PR doing this for both Cloudformation and Terraform infrastructure stacks.

**Comment by cristim** [comment]
@binarylogic, @homme, @kkopachev please have a look at #205 and confirms if it solves your problem.

**Comment by cristim** [comment]
I just tried to reproduce this issue and I failed, for me the linked role for Spot was created IAM even if the AutoSpotting role doesn't have the 'CreateServiceLinkedRole' permission, this may have been just a glitch on the AWS side.

Can anyone else still reproduce this problem?

**Comment by cristim** [comment]
I couldn't reproduce this issue, please reopen if this is still a problem for you guys.
