### ISSUE TITLE
t2 instances are considered equal when they are not

### ISSUE THREAD

**Issue by binarylogic** [cristim/autospotting#190]
# Github issue #

## Issue type ##

- Bug Report

## Build number #

```text
build nightly-517 expiring on 09-Feb-2018
```

## Summary ##

We have an ASG configured to use `c5.2xlarge` instances, autospotting replaced them with `t2.2xlarge` instances. Correct me if I'm wrong, but `t2.2xlarge` instances are limited in their CPU usage, and as a result, they are inferior to `c5.2xlarge` instances.

## Expected results ##

To choose a replacement spot instance that, at the very least, matches the on-demand instance CPU available resources. Spot instances should not be inferior to the on-demand instance in a meaningful way.

**Comment by cristim** [comment]
I agree, but I think the t2 are still a viable option if their CPU is set to  not be throttled.

This would need to be enabled when requesting them,and the surcharge would have to be considered in the price comparisons.

Another much easier to implement but less sophisticated option is to simply skip the T2 instance types when the on-demand instance type is not burstable itself

**Comment by xlr-8** [comment]
I'd honestly be fine with the second solution, we we realize this is a blocking solution for certain person then we could re-consider implementing it as a an option such as 'StrictCPU' or something like this.

**Comment by binarylogic** [comment]
Agree. The current behavior violates the core premise of autospotting: autospotting should never downgrade an instance, it should be a completely transparent replacement to save on cost. If someone is ok with `t2` instances that should be opt-in.

**Comment by xlr-8** [comment]
Although we could imagine, to always select [unlimited t2](https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v11237-2017-11-30) in order to avoid this, but cost would become then less controlled.

**Comment by xlr-8** [comment]
As the [PR](https://github.com/cristim/autospotting/pull/196) was merged, I'll close that issue. Feel free to re-open it if you have extra comments / disagree.
