### ISSUE TITLE
Support allowed_instance_types for terraform

### ISSUE THREAD

**Issue by binarylogic** [cristim/autospotting#191]
# Github issue #

## Issue type ##

- Bug Report

## Summary ##

https://github.com/cristim/autospotting/issues/47 and https://github.com/cristim/autospotting/pull/120 describe an `allowed_instance_types` option that is not exposed as a terraform variable. I'm unsure if the lambda function supports this, but it would be nice to expose this option.

Also, thank you for your work on this, it's been very helpful for us.

**Comment by cristim** [comment]
Thanks for reporting this, if you are really interested about this please consider contributing a pull request to fix it.
