### ISSUE TITLE
c5.* instances do not have virtualization types

### ISSUE THREAD

**Issue by binarylogic** [cristim/autospotting#193]
# Github issue #

## Issue type ##

- Bug Report

## Build number #

```text
8cacef3728a6ee670c3d9a627bb60181ce987c0d
```

## Summary ##

`c5.*` instances return a empty slice of virtualization types, which consistently excludes them during the [`isVirtualizationCompatible` check](https://github.com/cristim/autospotting/blob/8cacef3728a6ee670c3d9a627bb60181ce987c0d/core/instance.go#L213).

## Steps to reproduce ##

Set `allowed_instance_types` to any `c5.*` instance (assuming it meets the resource requirements of the current on-demand instance.

**Comment by cristim** [comment]
Thanks for the report, this looks like an upstream bug, we will need to update the instance type information on the upstream dependency project https://github.com/cristim/ec2-instances-info

**Comment by cristim** [comment]
This should be fixed in 4732df0682725ac7460c06e981df50c03c1b19c2, please try a newer build and reopen if it's still broken.

**Comment by binarylogic** [comment]
Confirmed that it’s fixed for me. Thanks!
