### ISSUE TITLE
Security group does not exist in VPC

### ISSUE THREAD

**Issue by sheldon-sminq** [cristim/autospotting#195]
# Github issue #

## Issue type ##

- Bug Report

## Build number #

```
nightly-539 expiring on 15-Feb-2018
```

## Configuration ##

AllowedInstanceTypes | c4.large,t2.large,m4.large |  
-- | -- | --
BiddingPolicy | normal |  
ExecutionFrequency | rate(5 minutes) |  
LambdaHandlerFunction | handler.Handle |  
LambdaMemorySize | 256 |  
LambdaS3Bucket | cloudprowess |  
LambdaZipPath | nightly/lambda.zip |  
LogRetentionPeriod | 7 |  
MinOnDemandNumber | 1 |  
MinOnDemandPercentage | 0.0 |  
OnDemandPriceMultiplier | 1.0 |  
Regions | ap-south* |  
SpotPricePercentageBuffer | 10.0

## Environment ##

- AWS region
- Type of environment: (VPC, EC2Classic or DefaultVPC)
- Anonymized launch configuration: 

``ap-south-1
   DefaultVPC
  
```

## Summary ##

<!-- Explain the problem briefly -->

## Steps to reproduce ##

<!--
For bugs, show exactly how to reproduce the problem, using a minimal test-case.
For new features, show how the feature would be used and explain what benefits
it would bring to the other users.
-->

<!-- You can also paste gist.github.com links for larger content -->

## Expected results ##

Installed autospotting in the east region, updated tag in my elasticbeanstalk instances with auto-enabled = true. Set the following properties

## Actual results ##

<!-- What actually happened? -->
logs see the following errors "utoscaling.go:711: Failed to create spot instance request for awseb-e-quvzk3r97n-stack-AWSEBAutoScalingGroup-PATSOSOV904B InvalidGroup.NotFound: The security group 'awseb-e-quvzk3r97n-stack-awsebsecuritygroup-v9qlvd4xw7j3' does not exist in VPC 'vpc-744caa1d'
<!--
You can paste some logging output and/or a stack trace between quotes below
-->

```
018/01/04 08:39:30 autoscaling.go:852: awseb-e-quvzk3r97n-stack-AWSEBAutoScalingGroup-PATSOSOV904B Found 0 d2.4xlarge instances
2018/01/04 08:39:30 autoscaling.go:673: Finished searching for best spot instance in ap-south-1a
2018/01/04 08:39:30 autoscaling.go:674: Replacing an on-demand c4.large instance having the ondemand price 0.11
2018/01/04 08:39:30 autoscaling.go:676: Launching best compatible instance: t2.large with the current spot price: 0.0271
2018/01/04 08:39:30 autoscaling.go:686: Bidding for spot instance for awseb-e-quvzk3r97n-stack-AWSEBAutoScalingGroup-PATSOSOV904B
2018/01/04 08:39:30 autoscaling.go:629: BiddingPolicy: normal
2018/01/04 08:39:30 autoscaling.go:632: Launching spot instance with a bid = 0.11
2018/01/04 08:39:30 autoscaling.go:711: Failed to create spot instance request for awseb-e-quvzk3r97n-stack-AWSEBAutoScalingGroup-PATSOSOV904B InvalidGroup.NotFound: The security group 'awseb-e-quvzk3r97n-stack-awsebsecuritygroup-v9qlvd4xw7j3' does not exist in VPC 'vpc-744caa1d'
status code: 400, request id: 740f1589-ff13-4f63-b8d3-b4a08b9707b0 {
BlockDeviceMappings: [{
DeviceName: "/dev/xvda",
Ebs: {
VolumeSize: 30,
VolumeType: "gp2"
}
},{
DeviceName: "/dev/xvdcz",
Ebs: {
DeleteOnTermination: true,
VolumeSize: 12,
VolumeType: "gp2"
}
}],
EbsOptimized: false,
IamInstanceProfile: {
Name: "aws-elasticbeanstalk-ec2-role"
},
ImageId: "ami-3b3f4054",
InstanceType: "t2.large",
KeyName: "Sminq",
Monitoring: {
Enabled: false
},
NetworkInterfaces: [{
DeviceIndex: 0,
Groups: ["awseb-e-quvzk3r97n-stack-AWSEBSecurityGroup-V9QLVD4XW7J3"],
SubnetId: "subnet-53c7213a"
}],
Placement: {
AvailabilityZone: "ap-south-1a"
},
```

**Comment by cristim** [comment]
This seems to be a duplicate of #48, until that one is fixed the only workaround is to run your stack in a non-default VPC
