### ISSUE TITLE
Support disallowed_instance_types for terraform

### ISSUE THREAD

**Issue by CpuID** [cristim/autospotting#198]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

https://github.com/cristim/autospotting/pull/196 adds the `disallowed_instance_types` option that is not exposed as a terraform variable. It would be nice to expose this, equivalent to Cloudformation.

Re https://github.com/cristim/autospotting/commit/58bb1c128892b6272a5266cf7526cf8865d37028#commitcomment-26676827  :)

cc @binarylogic

**Comment by xlr-8** [comment]
Could be good to reply and/or take into account some of the comments made as well https://github.com/cristim/autospotting/pull/196#pullrequestreview-87979399
