### ISSUE TITLE
Feature Idea - Filter tags for OnDemandPriceMultiplier option

### ISSUE THREAD

**Issue by kaitea** [cristim/autospotting#212]
Hi,

For some of the config options like OnDemandPriceMultiplier, it would be nice if the user can specify  more than one and it's only applicable if it matches a supplied filter tag.

Thanks

**Comment by xlr-8** [comment]
Could you provide some more information about the use case, or what you have in mind?

If I understood your need correctly, I believe that if [this PR](https://github.com/cristim/autospotting/pull/209) gets merged, you might simply run multiple instances of autospotting with extra tags, and various parameters.

**Comment by cristim** [comment]
This should be doable with multiple installations of the AutoSpotting Lambda function, each configured with its own tag filters.

@kaitea please re-open if you have any issues configuring this.
