### ISSUE TITLE
Support installing Lambda code from S3

### ISSUE THREAD

**Issue by grahamlyons** [cristim/autospotting#223]
# Github issue #

## Issue type ##

- Feature Idea

## Build number #

```text
965aa93
```

## Summary ##

We have a CI pipeline and build the Lambda code at the start, push to S3 and then install into different environments by pulling down from S3, in the same way that you might use a more traditional build artefact (RPM, DEB, JAR, etc. etc. etc.)

It would be nice to be able to use the Terraform code provided here but to pass the `s3_bucket` and `s3_key` parameters to the `aws_lambda_function` resource, instead of referencing a local file.

Is this something that you'd be keen/happy to see as a feature? If so, I'll happily raise a pull request.

**Comment by cristim** [comment]
@grahamlyons that's exactly what we do from CloudFormation. 

I'd gladly accept such a PR for Terraform, but please make it configurable and keep the current behavior by default in order to support existing installations as they are.

**Comment by grahamlyons** [comment]
Of course. Thanks for the quick reply.
