### ISSUE TITLE
Panic: Runtime Error

### ISSUE THREAD

**Issue by truongvinhtien** [cristim/autospotting#229]
Hi, I was trying to run autospotting locally but had the panic error. May I ask what cause this problem?
## Issue type ##
- Bug Report
## Environment ##
- AWS region
- Type of environment: EC2
## Steps to reproduce ##
Run command: autospotting

## Actual results ##
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4b2ec7]

goroutine 199 [running]:
panic(0xa82460, 0xc42000c100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cristim/autospotting/core.(*autoScalingGroup).havingReadyToAttachSpotInstance(0xc4205c2900, 0xc421253d01, 0x2)
	/home/tien/Desktop/Workplace/go/src/github.com/cristim/autospotting/core/autoscaling.go:595 +0xaf7
github.com/cristim/autospotting/core.(*autoScalingGroup).process(0xc4205c2900)
	/home/tien/Desktop/Workplace/go/src/github.com/cristim/autospotting/core/autoscaling.go:305 +0x2ce
github.com/cristim/autospotting/core.(*region).processEnabledAutoScalingGroups.func1(0xc4200988f0, 0xc420301040, 0xc4202ca850, 0xe, 0xc4200988f0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/tien/Desktop/Workplace/go/src/github.com/cristim/autospotting/core/region.go:396 +0x74
created by github.com/cristim/autospotting/core.(*region).processEnabledAutoScalingGroups
	/home/tien/Desktop/Workplace/go/src/github.com/cristim/autospotting/core/region.go:398 +0x127

**Comment by cristim** [comment]
Good catch, looks like we missed a nil-check. 

I didn't see it before, there must be some condition in your account that triggered it.

I will have a look at this later today.

**Comment by cristim** [comment]
FIxed in d653fb3.

**Comment by truongvinhtien** [comment]
It worked perfectly! Thank you!
