### ISSUE TITLE
Unable to import module 'handler': No module named handler #233

### ISSUE THREAD

**Issue by prashantdj1** [cristim/autospotting#234]
I am installing via terraform... Can you just tell me what will be the handler.. I changed to go1 but below error:

fork/exec /var/task/handler.Handle: no such file or directory: PathError

**Comment by prashantdj1** [comment]
what will be the handler ?

**Comment by prashantdj1** [comment]
done.. resolved.

**Comment by xlr-8** [comment]
If you believe there is a need to update the documentation, feel free to let us know
