### ISSUE TITLE
Mitigate the pending SIRs caused by stable spot prices

### ISSUE THREAD

**Issue by cristim** [cristim/autospotting#240]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

The stable spot prices can often cause spot instance launch failures due to unavailable capacity even when the spot price is significantly lower than the bid price.

In order to mitigate this we have a couple of options:
- Measure the amount of time the SIRs have been in pending states, and temporarily blacklist the instance types that failed to launch within a few minutes then cancel the pending SIRs.
- Launch multiple SIRs in parallel for all the compatible instance types, in the increasing order of their hourly price, sleeping for a while between launching the new SIR, until we get a running instance. Then cancel all the redundant SIRs and terminate all the additional instances that may have been launched. With per-second billing, this price is likely negligible and likely less than the price paid to run the on-demand instance for longer time in case we fail to run any on-demand instances and blacklist spot instance types.

**Comment by CpuID** [comment]
Related: https://github.com/cristim/autospotting/issues/166

**Comment by xlr-8** [comment]
I feel like both ways are workaround, but the type that seem a bit more 'hacky' to me; and yet I'm sorry but I do not have anything better to offer than this.

I'll keep you posted, if I think about anything

**Comment by cristim** [comment]
This was largely addressed by #257, we now fail to launch the instance in the current run if the SIR failed to launch an instance within some 30s or so.

Going forward, in #263 we'll try multiple instance types after the first failed.
