### ISSUE TITLE
Using filter tags with wildcard does not work

### ISSUE THREAD

**Issue by kaitea** [cristim/autospotting#246]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##
For us, using filter tags with wildcard does not work.
For example, when setting TAG_FILTERS=spot-enabled=true,Environment=sandbox* , autospotting does not perform any action since no instances match (where Environment could be sandbox-teama, sandbox-teamb, etc..)

**Comment by cristim** [comment]
Thanks for reporting this.

As far as I can tell this is normal behavior as per the current implementation, so it's just a missing feature.

If you want this badly enough please consider contributing this feature, we'll gladly help you in case you need assistance.

**Comment by cristim** [comment]
@kaitea this is now available thanks to a contribution by @mrmod.

Please give it a try and report any issues.
