### ISSUE TITLE
On Demand Tags Incorrect

### ISSUE THREAD

**Issue by aaronthebaron** [cristim/autospotting#253]
# Github issue #

PR Incoming

## Issue type ##

- Documentation Report

## Build number #

N/A

## Configuration ##

N/A

## Environment ##

N/A

## Summary ##

The tags for autospotting_min_on_demand_percentage and autospotting_min_on_demand_number were incorrectly specified in the documentation as autospotting_on_demand_percentage and autospotting_on_demand_number.

## Steps to reproduce ##

[The code where the actual tags are specified is here.](https://github.com/cristim/autospotting/blob/69ed6177f6d06324e3b962080807977751cb2f21/core/autoscaling.go)

## Expected results ##

Tag to be correct.

## Actual results ##

Not correct! 😄

**Comment by cristim** [comment]
Fixed in #254
