### ISSUE TITLE
Add to terraform registry 

### ISSUE THREAD

**Issue by neillturner** [cristim/autospotting#259]
## Issue type ##

- Feature Idea

## Summary ##

It would be great if you could add this to the terraform registry under say autospotting as it would make it dead easy to install.

**Comment by cristim** [comment]
Thanks for the proposal, I'll add it.

**Comment by neillturner** [comment]
I put in terraform registry at: 
  https://registry.terraform.io/modules/neillturner/autospotting/aws

**Comment by cristim** [comment]
Thanks for your contribution.

I guess that makes you a maintainer for our Terraform code :-)
