### ISSUE TITLE
Not able to create custom binaries

### ISSUE THREAD

**Issue by spadmanabhanvnera** [cristim/autospotting#260]
# Github issue #
go build is not creating binaries.

## Issue type ##

- Bug Report

## Build number #

commit bf1a76baed5abbcea0d3f9249916a8b876cb548d (HEAD -> master, origin/master, origin/HEAD)
Author: Cristian Măgherușan-Stanciu @magheru_san <cristim@users.noreply.github.com>
Date:   Sun May 27 12:05:37 2018 +0200

    Update README.md

```
I am trying to create a custom binary by following https://github.com/cristim/autospotting/blob/master/CUSTOM_BUILDS.md

In the last step, I do go build, but there is no build generated.

$ make full-test
error	some files did not pass go fmt, fix the following formatting diff:
make: *** [fmt-check] Error 1

Is there a step that I am missing. 
```

## Configuration ##

Mac OS

## Environment ##

```
$ go version
go version go1.10.1 darwin/amd64
$ git version
git version 2.15.0
$ aws --version
aws-cli/1.15.4 Python/3.5.0 Darwin/16.7.0 botocore/1.10.4
```

## Summary ##

Running go build on ~/godev/src/github.com/cristim/autospotting does not create binaries as intended.
$ make full-test
error	some files did not pass go fmt, fix the following formatting diff:
make: *** [fmt-check] Error 1

## Steps to reproduce ##

Followed the steps given in https://github.com/cristim/autospotting/blob/master/CUSTOM_BUILDS.md
to compile binaries locally.

## Expected results ##

build folder with the binary will be created

## Actual results ##

no build folder present

**Comment by cristim** [comment]
Thanks for reporting this.

Unfortunately I don't have time to look into this anytime soon, for now all I can advice is to just use the official binaries.

But if you manage to get to the bottom of it, I'd love to see a PR addressing this issue.

**Comment by lenucksi** [comment]
I experienced the same problem and will have a look at it later this week. Maybe that will yield a matching PR ;)

**Comment by lenucksi** [comment]
Alright, I've had a look the problem and came up with a solution. 
The culprit is the wc command provided by OSX.

```
$ gofmt -l -s ./core/config.go ./core/instance.go ./core/launch_configuration.go ./core/connections.go ./core/region.go ./core/region_test.go ./core/instance_test.go ./core/launch_configuration_test.go ./core/connections_test.go ./core/spot_price_test.go ./core/autoscaling_test.go ./core/spot_price.go ./core/mock_test.go ./core/autoscaling.go ./core/main.go ./core/main_test.go ./autospotting.go | wc -l
```
yields

```
       0
```
which is then compared to ```0``` using

```
ifneq ($(shell gofmt -l -s $(GOFILES) | wc -l), 0)
````
Which ends up in the if clause in any case.

Gnu coreutils, included with all Linux-Distros and Homebrew, output the expected ```0``` and thus, the Makefile works.
An approach to fixing this would be ```tr``` or, even simpler, ```xargs``` to trim away possibly existing spaces in the output of ```wc```.

I'll create PR for the solution.
