### ISSUE TITLE
Ignore instances with instance protection enabled

### ISSUE THREAD

**Issue by codejamninja** [cristim/autospotting#267]
Instances that have instance protection should be ignored

**Comment by codejamninja** [comment]
Fixed with #269

**Comment by cristim** [comment]
I think we may also want to ignore the instances with the API termination protection flag set.

This is an EC2 feature, unlike the scale-in protection, which is an AutoScaling feature. This means it's set on the ec2.Instance object.

**Comment by cristim** [comment]
I'll look into this tomorrow.

**Comment by cristim** [comment]
Fixed in #275.
