### ISSUE TITLE
New instances fail to obtain public IP

### ISSUE THREAD

**Issue by binarylogic** [cristim/autospotting#274]
## Issue type ##

- Bug Report

## Summary ##

We recently updated to the latest version of the lambda function and new spot instances no longer receive public IPs when launching. This caused our instances to be unusable and subsequently took down those instances. Rolling back to our previous version (`nightly-878`) resolved the issue. Unfortunately I don't have more information but wanted to open a ticket since this effectively renders autospotting unusable for us.

**Comment by cristim** [comment]
This was briefly broken after merging #257, but should be fixed in lambda_build_882.zip, please let me know if you still have any issues with that.

**Comment by cristim** [comment]
closing issue

@binarylogic  please re-open if you still have any issues
