### ISSUE TITLE
Switch to RunInstances API leads to 403 UnauthorizedOperation errors

### ISSUE THREAD

**Issue by lukvdborne** [cristim/autospotting#289]
# Github issue #

## Issue type ##

- Bug Report

## Build number #

```
nightly-794
```

## Configuration ##

-

## Environment ##

- eu-west-1
- Type of environment: VPC
- Anonymised launch configuration:

```
  autospotting_allowed_instance_types = "t2.small"
  autospotting_min_on_demand_number = "1"
  autospotting_min_on_demand_percentage = "50.0"
  autospotting_regions_enabled = "eu-west-1"
  autospotting_tag_filters = "spot-enabled=true"
  autospotting_on_demand_price_multiplier = "1.0"
  autospotting_spot_price_buffer_percentage = "10.0"
  autospotting_bidding_policy = "normal"
  autospotting_spot_product_description = "Linux/UNIX (Amazon VPC)"

  lambda_zipname = "../modules/autospotting/lambda.zip"
  lambda_runtime = "go1.x"
  lambda_memory_size = "256"
  lambda_timeout = "300"
  lambda_run_frequency = "rate(5 minutes)"
  lambda_tags = {}

```

## Summary ##

It appears the switch to the new RunInstance API call and the respective change in de autospotting-policy.json in commit ea38ec20fd3726355f996d0efab9c08d2a5f1369 causes the following error:

```autoscaling.go:333: Could not launch cheapest spot instance: UnauthorizedOperation: You are not authorized to perform this operation.```

When we checkout the commit before the aforementioned commit it works fine again.

## Steps to reproduce ##

- Install the autospotting module from the master branch
- Look at the CW logs

## Expected results ##

- Autospotting should start

## Actual results ##

- We're getting 403 UnauthorizedOperation errors

**Comment by lukvdborne** [comment]
Do you mean this file? https://github.com/cristim/autospotting/blob/master/terraform/autospotting/autospotting-policy.json

It was automatically updated with the terraform init. We did remove the .terraform dir prior to (re)running `terraform init`

**Comment by cristim** [comment]
That should be fine, just make sure you run a recent autospotting version against it, the build 794 is 3 months old and won't work with this policy. The latest build as of now is 912.

**Comment by cristim** [comment]
@lukvdborne are you still experiencing this issue with the latest build?

**Comment by lukvdborne** [comment]
No I didn't look properly and wasn't aware the lambda wasn't part of the module but was a separate upload in the repository. It works with the latest build! Thanks!
