### ISSUE TITLE
Seeing "stranded" spot instances when minimum OD instances are configured

### ISSUE THREAD

**Issue by jjones-smug** [cristim/autospotting#290]
# Github issue #

## Issue type ##

- Bug Report

## Build number #

Custom build based on 24a5693f0c336f32fddce4fdaab87aeccca26d4f (from Jul 26, 2018)

Diff: https://gist.github.com/jjones-smug/7fe55c7015982411a92f30b31298d529

We also use a different setup for IAM permissions, but I don't think that's relevant.  I can share those if necessary but want to avoid to much SPAM.

## Configuration ##

Our configuration is pretty simplistic/vanilla.  The one thing that I think is important for this issue is that we do specify a minimum number of OD instances for some of our ASG's.  And those are the ones where we're seeing the "stranded" spot instances.

## Environment ##

- us-east-1
- VPC
- Anonymized launch configuration:

We run multiple Lambda's with different configurations, and multiple ASG's with different tags/configs as well.  And it's all in modularized Terraform configurations so it's hard to post a single launch configuration.  If it's necessary I can come up with something, but I think the issue is just related to the use of a minimum OD number for an ASG.

## Summary ##

We're seeing spot instances launched by the Autospotting lambda that are left running and not swapping into the ASG for which they were intended.  It looks like the code is launching the spot instances anytime there's at least one OD instance in the ASG.  But the subsequent code that checks to see if it's OK to swap it into place, by checking the "grace period" and the minimum number of OD instances, decides to wait indefinitely.  Today a monitoring script noticed spot instances that were running for several days without being associated with an ASG.

## Steps to reproduce ##

- Setup an ASG with min instances set to 2, max instances set to 3
- Configure the ASG with an Autospotting tag setting minimum number of OD instances to 1.
- Launch the ASG with 2 instances and wait for Autospotting to run.
- It will replace one of the instances normally with a spot instance, then launch a second spot instance.  That second spot instance will not be swapped into the ASG, since at least one OD instance must be allocated.
- Subsequent Autospotting runs will log "Waiting for next run while processing ASG" each time is scans the ASG, but leave the spot instance running.

- Then increase the ASG to 3 instances.
- Wait for the next Autospotting run and the 2nd spot instance that was launched previously will be swapped into the ASG.

## Expected results ##

I include the expected/actual results with the description.

## Actual results ##

I include the expected/actual results with the description.

I believe that one way to prevent Autospotting from launching spot instances that will be blocked from use later, is to bracket this call,

```
err := onDemandInstance.launchSpotReplacement()
```
in the process() routine in "autoscaling.go" with a call to the minimum OD instance check routine.

**Comment by cristim** [comment]
@jjones-smug thanks for reporting this, it definitely looks like a regression of the recent RunInstances change, sorry about that.

Unfortunately I'm busy with other stuff these days so I won't be able to help you with this, but by all means please give that a try and if you get it working properly without introducing another regression for other use cases, I'll definitely accept a PR for this issue.

**Comment by jjones-smug** [comment]
Working on it today...  Thanks!

**Comment by aaronthebaron** [comment]
Thanks @jjones-smug I've got this issue as well. Let me know if I can test a fix in my cluster.

**Comment by jjones-smug** [comment]
testing it now.  It's really simple, so here's a GIST if you want to try it in parallel.

https://gist.github.com/jjones-smug/7d04d6ecf52973fcf58a034c90f34468

**Comment by jjones-smug** [comment]
Tested fine for us, we've pushed it live as of a few minutes ago.  I'll work on getting a PR submitted this evening.
