### ISSUE TITLE
Take into account the current reserved instance usage before launching spot instances 

### ISSUE THREAD

**Issue by cristim** [cristim/autospotting#30]

**Comment by roeyazroel** [comment]
It's hard to know if the instance that you're replacing is RI or not, there is no indication if this instance is an RI.

You will need to check if there is a RI subscription for this instance type, and if this RI subscription does exists, you will need to verify that there is no other instance of this type... so basically, I think that RI doesn't need to be take care of within autospotting.

**Comment by cristim** [comment]
That was pretty much the idea: to stop from replacing on-demand instances once the number of running on-demand instances is matching the number of reserved instances for that instance type for that particular AZ.

**Comment by cristim** [comment]
I think the change done in #54 provides enough functionality to cover this use case pretty well.
