### ISSUE TITLE
Paginate all API calls where it is applicable

### ISSUE THREAD

**Issue by cristim** [cristim/autospotting#37]
This issue was discovered in #36, it may become a problem on AWS accounts with lots of resources.

**Comment by jwineinger** [comment]
#39 fixes some of this by using the paginated calls for describing autoscaling group tags and the following call to describe autoscaling groups.

**Comment by cristim** [comment]
I think we can close this for now, and open other individual issues whenever we find other non-paginated API calls that cause issues.
