### ISSUE TITLE
Whitelist/blacklist certain instance types via configuration

### ISSUE THREAD

**Issue by cristim** [cristim/autospotting#47]
I saw forks that hard-coded some specific instance types they need in their environment. Other people complained that some instances are problematic in certain availability zones and had them hardcoded out.

This could be configurable using CloudFormation stack parameters, passed as variables to the Lambda function now that Lambda supports this feature. We could add two new CloudFormation stack options:

```
WhiteListedInstanceTypes: m3.medium,c4.large
BlackListedInstanceTypes: c3.large
```

On another hand I think that such a global setting may not be desirable for some cases, so it may be better to also be able to apply it on a per-group basis, using additional tags set on the AutoScaling group:

```
AutoSpotting_WhiteListedInstanceTypes: c3.large,c4.large
AutoSpotting_BlackListedInstanceTypes:  c3.xlarge
```

**Comment by roeyazroel** [comment]
I think that it will be very useful.

Maybe also add "family" tag?  
AutoSpotting_WhiteListedInstanceTypesFamily: c3, c4
AutoSpotting_BlackListedInstanceTypesFamily:  m4

**Comment by cristim** [comment]
@roeyazroel I think it's better to have it based on globs, just like we have for the new region filter.

As for the names of the configuration options, they should be underscore_separated_only, just like we have the new options used for the on-demand capacity configuration.

**Comment by cristim** [comment]
This is being implemented in #120

**Comment by cristim** [comment]
#120 implements instance type whitelisting without globs as well as an option of keeping the original instance type, whatever that is.

**Comment by cristim** [comment]
I think we can close this, recent builds support both filtering modes

**Comment by xlr-8** [comment]
Has the whitelisting been validated as bug less? I haven't got the chance to do so, some users seem to use it fine, while I remember some other reported issues.

**Comment by cristim** [comment]
The reports I've seen so far were about side effects of running the replacement algorithm with fewer instance types to choose from.
