### ISSUE TITLE
Pick the replaced on-demand instances based on the uptime

### ISSUE THREAD

**Issue by cristim** [cristim/autospotting#66]
The instances should be replaced in a way that minimizes the wasted runtime hours that the user gets charged. We should pick the on-demand instance which will be closer to a full instance hour when eventually terminated.

Max((uptime_minutes + grace_period_minutes + 15 ) % 60)

The 15min is a buffer that allows us to launch a spot instance and replace the on-demand one. It could also be parameterized, although I don't think it worth the effort.

**Comment by roeyazroel** [comment]
I just wanted to open a issue about this case.

We have an cluster that every hour as an peak and scale out, and autospooting make it more expensive as the scaled out on demand instances replace with an spot instance and after less than 20 minutes when the peak was over EBS scaled in. So we payed twice, for the on demand and for the spot.

This is very important feature!

**Comment by cristim** [comment]
AutoSpotting is designed for environments where the capacity is more or less constant or maybe fluctuating on a daily basis so that the on-demand instances are rarely used, otherwise they may dominate your costs.

Fixing this issue will not help your use case, it's just a small optimization, so that when we have more on-demand instances in the group we just pick for replacement the one closer to a full hour in order to slightly reduce wasted on-demand hours.

If you need to scale in and out on an hourly basis maybe you can increase the capacity to match the peak and make your scale-down policy less aggressive so you keep more or less constant capacity. For example on one of my environments when I scale out I double capacity when over 50% CPU usage for more than 5min, then for scale in I half the capacity when CPU usage is less than 10% for at least an hour.

Or you can use a spot-fleet which never runs any on-demand nodes, since it can now scale out using policies.

**Comment by roeyazroel** [comment]
I agree that making the cluster less dynamic will be easier for autospotting to deal with.

But if autospotting will check if the on demand instance is near one hour up time since launch, it still will take care dynamic clusters as the temporary instances that join the cluster for the peak will be terminate if the peak was less than 1 hour, and if it is more than 1 hour, then autospotting still can help.

**Comment by cristim** [comment]
I don't think I understand what you meant.

Autospotting has no way to tell how long is your peak, you have to tweak your policies so that scaling is not happening on a hourly basis, even if that means over-provisioning some capacity.

**Comment by roeyazroel** [comment]
Sure it doesn't and it shouldn't.

What I meant is that if the ASG does a scale out, and new on demand instance was launch, this instance shouldn't be replaced until you will consume the one hour that you already paid for once you launch it.

Once autospotting will be aware of the launch time of the on demand instance, also dynamic ASG will be able to benefit from it.

**Comment by cristim** [comment]
That makes sense now, but the instance replacement procedure has to start earlier, if the group has a grace period:

Let's assume an on-demand instance is started at 1:00 PM, and the group has 20min grace period.

With the current algorithm, the replacement spot instance would be launched immediately(in the next autospotting run) and the on-demand instance would be replaced and terminated soon after its uptime is a bit over 20min, wasting almost 40min of that on-demand hour.

What I understand from what you is to wait a while before replacing it so we can benefit from that on-demand instance for as much as possible.

We could postpone the launch for a while (let's say until about 1:30 PM), so that the on-demand instance is closer to its first entire hour when being terminated, but definitely not right after that hour has passed.

We can always pick the machine with (uptime + grace period) around 50min, and if the machines are relatively new we should wait until this value reaches 50min.

**Comment by roeyazroel** [comment]
Sounds good.

I'm not yet familiar with GO unfortunately, so it will take me some time to work on it.

**Comment by cristim** [comment]
I hope it's not do hard, but if you have any questions feel free to reach out on gitter.

**Comment by cristim** [comment]
This is no longer relevant, AWS will soon charge EC2 instances on a per-second basis:
https://aws.amazon.com/blogs/aws/new-per-second-billing-for-ec2-instances-and-ebs-volumes/
