### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by phils** [cristim/autospotting#83]
Just trying out this tool (thanks!)... and had this panic on the first run (after it had spun up the first replacement spot instance).   Hope the stack trace gives you enough info.  It panics after launching each spot instance (it happened again for the 2nd box).

2017/02/20 10:01:10 spot_instance_request.go:91: example-asg successfully tagged spot instance request (removed)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7efdc89fafa4]

goroutine 32 [running]:
panic(0x7efdc916d920, 0xc420012040)
/usr/local/go/src/runtime/panic.go:500 +0x1a5
github.com/cristim/autospotting/core.(*autoScalingGroup).bidForSpotInstance(0xc4203ae690, 0xc4205e23c0, 0x3fa0624dd2f1a9fc)
/go/src/github.com/cristim/autospotting/core/autoscaling.go:599 +0x354
github.com/cristim/autospotting/core.(*autoScalingGroup).launchCheapestSpotInstance(0xc4203ae690, 0xc4204982c8)
/go/src/github.com/cristim/autospotting/core/autoscaling.go:556 +0x969
github.com/cristim/autospotting/core.(*autoScalingGroup).process(0xc4203ae690)
/go/src/github.com/cristim/autospotting/core/autoscaling.go:213 +0x691
github.com/cristim/autospotting/core.(*region).processEnabledAutoScalingGroups.func1(0xc420588870, 0xc42041ca00, 0xc4203c5ba0, 0xc, 0xc420588870, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/cristim/autospotting/core/region.go:315 +0x6f
created by github.com/cristim/autospotting/core.(*region).processEnabledAutoScalingGroups
/go/src/github.com/cristim/autospotting/core/region.go:317 +0x105
END RequestId: 7db18159-f753-11e6-8c9c-b7d0b6616b0a
REPORT RequestId: 7db18159-f753-11e6-8c9c-b7d0b6616b0a Duration: 5220.57 ms Billed Duration: 5300 ms Memory Size: 256 MB Max Memory Used: 26 MB
RequestId: 7db18159-f753-11e6-8c9c-b7d0b6616b0a Process exited before completing request

**Comment by cristim** [comment]
Thanks for reporting this, I haven't seen this before.

Try to use another build, and it would be awesome if you can bisect it to find the build which introduces this issue.

Can you give a few details about your environment, so we can reproduce the problem? These should be enough for a start:

- AWS region
- anonymized output of `aws autoscaling describe-launch-configurations --launch-configuration-names your-launch-configuration`

**Comment by phils** [comment]
I specified only ap-southeast-2 in the cloudformation launch wizard
environment is VPC

launch config as requested:

`{
    "LaunchConfigurations": [
        {
            "UserData": removed,
            "IamInstanceProfile": "MyServerInstanceProfile",
            "EbsOptimized": false,
            "PlacementTenancy": "default",
            "LaunchConfigurationARN": "arn:aws:autoscaling:ap-southeast-2:accountnumberremoved:launchConfiguration:coderemoved:launchConfigurationName/nameremoved",
            "InstanceMonitoring": {
                "Enabled": true
            },
            "ClassicLinkVPCSecurityGroups": [],
            "CreatedTime": "2017-02-20T09:33:12.120Z",
            "BlockDeviceMappings": [],
            "KeyName": "removed",
            "SecurityGroups": [
                "sg-1234",
                "sg-5678"
            ],
            "LaunchConfigurationName": "nameremoved",
            "KernelId": "",
            "RamdiskId": "",
            "ImageId": "ami-1e47407d",
            "InstanceType": "t2.small",
            "AssociatePublicIpAddress": true
        }
    ]
}
`

**Comment by cristim** [comment]
Thanks, I think I already found the problem, fixing it in a few minutes.

**Comment by cristim** [comment]
@phils please try with the build 261, this issue should be fixed there and your spot machines should be handled properly from now on.

I'm sorry for this issue, I hope it didn't scare you away from the project :)

Please file other issues if you notice anything else not working as expected.

**Comment by xlr-8** [comment]
@cristim / @phils I confirm, after testing quickly via a new ASG/LC, I didn't have a problem with spawning a new spot instance to my ASG.

**Comment by cristim** [comment]
I think this is actually a pretty harmless error because the spot instance was launched, the spot instance request was tagged properly with no errors and we just panic'd in a stupid way because we expected it to actually fail to be tagged.

Those instance requests should have been handled properly in the next run of the lambda function.

**Comment by phils** [comment]
Thanks.. updated and not seeing the panic anymore.

**Comment by cristim** [comment]
Cool, glad it helped.

Let us know if you have any other feedback.
