### ISSUE TITLE
 React on the 2min termination notice

### ISSUE THREAD

**Issue by cristim** [cristim/autospotting#9]
Each of the instances about to be terminated can poll a metadata entry which will specify when the termination is imminent.

This should be handled in some way that may be specific to the application, so the user should be allowed to run some code that cleanly takes that instance out of the pool.

**Comment by seme1** [comment]
Would it be possible to use this termination notice by the Autopsotting algorithm in order to initiate the replacement for the currently running instance and hence minimize the replacement time ??

**Comment by cristim** [comment]
That would indeed save a few minutes of reduced capacity, but I think it won't be enough to completely mitigate it. There will be reduced capacity for a while because it won't be able to give you a new instance that fast, to seamlessly replace the old one. And all this at the cost of more complexity in the autospotting logic, which I'm trying to keep as simple as possible.

I honestly don't think the benefit worth it, at least not anytime soon. But thanks nevertheless, I will keep this idea in mind when I get to handling this termination notification.

But if you strongly believe in this, feel free to implement it in a branch, test it to determine if there is a significant benefit and if it does, I would be more than happy to merge this kind of pull request.

**Comment by cristim** [comment]
It seems there are existing tools that can be used from the user_data script to take action when the instance receives the spot termination notice.

For example [acksin/seespot](https://github.com/acksin/seespot) should do the trick, but what actions it should take depends a lot on the application, so we can't provide a generic solution.

We can only point to it(and maybe other similar tools can be added later) and recommend users to make use of it. I documented this in the Best Practices section of the README.md and I think that should be enough for now.
